language: csharp
solution: TestTravisCI.sln
install:
  - nuget restore TestTravisCI.sln
  - nuget install xunit.runners -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TestTravisCI.sln
  - mono ./testrunner/xunit.runners.console.2.1.0/tools/xunit.console.exe ./TestTravisCI.Tests/bin/Release/TestTravisCI.Tests.dll